// apps/web/src/pages/debts/ui/DebtorSection.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { Plus } from '@lucide/vue'
import type { Debtor } from '@expense-tracker/api'
import type { DebtDirection, DebtOperation } from '@/entities/debt-operation'
import { debtorSection } from '../model/selectors'
import DebtorRow from './DebtorRow.vue'
import { Button } from '@/shared/ui/button'

// One direction's section: header with the combined contact+debt add action,
// visible debtor rows, and settled (zero-balance) debtors behind a reveal.

const props = defineProps<{
  direction: DebtDirection
  debtors: readonly Debtor[]
  operations: readonly DebtOperation[]
}>()

const emit = defineEmits<{
  add: [direction: DebtDirection]
  select: [debtor: Debtor, direction: DebtDirection]
}>()

const { t } = useI18n()

const section = computed(() => debtorSection(props.debtors, props.operations, props.direction))

const title = computed(() =>
  props.direction === 'receivable' ? t('debts.receivable') : t('debts.payable'),
)
const addTitle = computed(() =>
  props.direction === 'receivable' ? t('debts.receivableAddTitle') : t('debts.payableAddTitle'),
)
const emptyText = computed(() =>
  props.direction === 'receivable' ? t('debts.receivableEmpty') : t('debts.payableEmpty'),
)

const showSettled = ref(false)
</script>

<template>
  <section>
    <div class="flex items-center justify-between">
      <h2 class="text-sm font-medium text-muted-foreground">{{ title }}</h2>
      <Button
        variant="ghost"
        size="icon"
        class="size-7 rounded-full"
        :aria-label="addTitle"
        :data-testid="`debts-section-add-${direction}`"
        @click="emit('add', direction)"
      >
        <Plus class="size-4" />
      </Button>
    </div>

    <div class="mt-1">
      <p v-if="section.visible.length === 0 && section.settled.length === 0" class="py-2 text-sm text-muted-foreground">
        {{ emptyText }}
      </p>
      <DebtorRow
        v-for="view in section.visible"
        :key="view.debtor.id"
        :debtor="view.debtor"
        :balance="view.balance"
        :direction="direction"
        @click="emit('select', view.debtor, direction)"
      />
      <button
        v-if="section.settled.length > 0"
        type="button"
        class="px-2 py-1 text-xs text-muted-foreground hover:underline"
        :data-testid="`debts-settled-reveal-${direction}`"
        @click="showSettled = !showSettled"
      >
        {{
          showSettled
            ? t('debts.hideSettled')
            : t('debts.showSettled', { count: section.settled.length })
        }}
      </button>
      <template v-if="showSettled">
        <DebtorRow
          v-for="view in section.settled"
          :key="view.debtor.id"
          :debtor="view.debtor"
          :balance="view.balance"
          :direction="direction"
          @click="emit('select', view.debtor, direction)"
        />
      </template>
    </div>
  </section>
</template>

// apps/mobile/src/pages/debts/ui/debtor-section.tsx
import { useState } from 'react'
import { View } from 'react-native'
import type { DebtDirection } from '@expense-tracker/api'
import { Text } from '@/shared/ui/text'
import { Pressable } from '@/shared/ui/pressable'
import { Icon } from '@/shared/ui/icon'
import { DEBT_DIRECTION_VIEWS } from '../model/kind'
import type { DebtorSectionView } from '../model/selectors'
import { DebtorRow } from './debtor-row'
import { Card } from '@/shared/ui/card'

/**
 * One direction's debtor list: section header with the circular «+» that
 * opens the combined contact+debt form for this direction (design D9),
 * balance-descending rows, and the settled (zero-balance) debtors hidden
 * behind a reveal row that carries the count.
 */
export function DebtorSection({
  direction,
  section,
  onDebtorPress,
  onAdd,
}: {
  direction: DebtDirection
  section: DebtorSectionView
  onDebtorPress: (debtorId: string, direction: DebtDirection) => void
  /** Opens the combined contact+debt sheet for this direction (page composition). */
  onAdd: (direction: DebtDirection) => void
}) {
  const view = DEBT_DIRECTION_VIEWS[direction]
  const [settledRevealed, setSettledRevealed] = useState(false)

  const rows = settledRevealed ? [...section.visible, ...section.settled] : section.visible

  return (
    <Card variant="elevated" className="gap-1" testID={`debts-section-${direction}`}>
      <View className="flex-row items-center justify-between">
        <Text variant="body" className="font-medium text-muted-foreground">
          {view.sectionTitle}
        </Text>
        <Pressable
          testID={`debts-section-add-${direction}`}
          accessibilityRole="button"
          accessibilityLabel={view.sheetTitle}
          className="active:opacity-70"
          onPress={() => onAdd(direction)}
        >
          <View className="h-10 w-10 items-center justify-center rounded-full bg-muted">
            <Icon name="add" size={24} colorClassName="accent-foreground" />
          </View>
        </Pressable>
      </View>

      {rows.length === 0 ? (
        <Text variant="body-sm" className="py-2 text-muted-foreground">
          {view.sectionEmpty}
        </Text>
      ) : (
        rows.map((row) => (
          <DebtorRow
            key={row.debtor.id}
            view={row}
            onPress={() => onDebtorPress(row.debtor.id, direction)}
          />
        ))
      )}

      {section.settled.length > 0 && (
        <Pressable
          testID={`debts-settled-reveal-${direction}`}
          accessibilityRole="button"
          className="py-2 active:opacity-70"
          onPress={() => setSettledRevealed((revealed) => !revealed)}
        >
          <Text variant="body-sm" className="text-muted-foreground">
            {settledRevealed
              ? // TODO(i18n): RU wording until mobile i18n wiring lands.
                'Скрыть рассчитавшихся'
              : `Показать рассчитавшихся (${section.settled.length})`}
          </Text>
        </Pressable>
      )}
    </Card>
  )
}
