// apps/web/src/pages/debts/ui/DebtorRow.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { ChevronRight } from '@lucide/vue'
import type { Debtor } from '@expense-tracker/api'
import { debtorAvatarColor, initialsOf } from '../model/selectors'
import { formatMoney, type CurrencyCode } from '@/shared/lib/money'
import { useSettingsStore } from '@/shared/store/use-settings-store'

const props = defineProps<{
  debtor: Debtor
  balance: number
}>()

const { locale } = useI18n()
const settings = useSettingsStore()
const displayCurrency = computed(() => settings.currency as CurrencyCode)

const balanceText = computed(() =>
  formatMoney(props.balance, displayCurrency.value, locale.value),
)
</script>

<template>
  <button
    type="button"
    class="flex w-full items-center gap-3 rounded-md px-2 py-2 text-left hover:bg-accent/50"
    :data-testid="`debts-debtor-${debtor.id}`"
    :aria-label="`${debtor.name}, ${balanceText}`"
  >
    <span
      class="flex size-9 shrink-0 items-center justify-center rounded-full text-xs font-semibold text-white"
      :style="{ backgroundColor: debtorAvatarColor(debtor.id) }"
      aria-hidden="true"
    >
      {{ initialsOf(debtor.name) }}
    </span>
    <span class="min-w-0 flex-1 truncate text-sm font-medium">{{ debtor.name }}</span>
    <span class="text-sm" :class="{ 'text-destructive': balance < 0 }">{{ balanceText }}</span>
    <ChevronRight class="size-4 shrink-0 text-muted-foreground" aria-hidden="true" />
  </button>
</template>

// apps/mobile/src/pages/debts/ui/debtor-row.tsx
import { View } from 'react-native'
import { Text } from '@/shared/ui/text'
import { Icon } from '@/shared/ui/icon'
import { Pressable } from '@/shared/ui/pressable'
import { cn } from '@/shared/lib/utils'
import type { DebtorBalanceView } from '../model/selectors'

// Brand accent tokens - vivid pops from the shared palette, hashed from the
// debtor id (no stored color: zero sync cost).
const AVATAR_COLORS = [
  'bg-brand-indigo',
  'bg-brand-violet',
  'bg-brand-lilac',
  'bg-brand-orange',
  'bg-brand-green',
  'bg-brand-leaf',
] as const

function avatarColorClass(id: string): string {
  let hash = 0
  for (let i = 0; i < id.length; i++) {
    hash = (hash * 31 + id.charCodeAt(i)) | 0
  }
  return AVATAR_COLORS[Math.abs(hash) % AVATAR_COLORS.length]
}

function initialsOf(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean)
  if (parts.length === 0) return '?'
  if (parts.length === 1) return parts[0]!.slice(0, 1).toUpperCase()
  return (parts[0]![0]! + parts[parts.length - 1]![0]!).toUpperCase()
}

export function DebtorRow({ view, onPress }: { view: DebtorBalanceView; onPress: () => void }) {
  return (
    <Pressable
      testID={`debts-debtor-${view.debtor.id}`}
      accessibilityRole="button"
      accessibilityLabel={`${view.debtor.name}, ${view.balanceText}`}
      className="flex-row items-center gap-3 py-3 active:opacity-70"
      onPress={onPress}
    >
      <View
        className={cn(
          'size-10 items-center justify-center rounded-full',
          avatarColorClass(view.debtor.id),
        )}
      >
        <Text variant="label" className="font-semibold text-primary-foreground">
          {initialsOf(view.debtor.name)}
        </Text>
      </View>
      <Text variant="body" className="flex-1 text-foreground" numberOfLines={1}>
        {view.debtor.name}
      </Text>
      <Text
        variant="body"
        className={cn('font-medium', view.balance < 0 ? 'text-destructive' : 'text-foreground')}
      >
        {view.balanceText}
      </Text>
      <Icon name="chevron-forward" size={16} colorClassName="accent-muted-foreground" />
    </Pressable>
  )
}
