// apps/web/src/shared/ui/donut-chart/ChartLegend.vue
<script setup lang="ts">
defineProps<{
  entries: readonly { id: string; label: string; color: string }[]
}>()
</script>

<template>
  <ul class="space-y-1.5" data-testid="chart-legend">
    <li v-for="entry in entries" :key="entry.id" class="flex items-center gap-2 text-sm">
      <span
        class="size-2.5 shrink-0 rounded-full"
        :style="{ backgroundColor: entry.color }"
        aria-hidden="true"
      />
      <span class="truncate">{{ entry.label }}</span>
    </li>
  </ul>
</template>

// apps/mobile/src/features/analytics/ui/chart-legend.tsx
import { View } from 'react-native'
import { Text } from '@/shared/ui/text'
import type { ChartEntry } from '../model/selectors'

export interface ChartLegendProps {
  entries: ChartEntry[]
  /** Row testIDs are `${testIdPrefix}-${entry.id}`. */
  testIdPrefix?: string
}

/** Color-dot rows mirroring exactly what the paired donut shows (same order). */
export function ChartLegend({ entries, testIdPrefix = 'analytics-legend' }: ChartLegendProps) {
  return (
    <View className="gap-2">
      {entries.map((entry) => (
        <View
          key={entry.id}
          className="flex-row items-center gap-2"
          testID={`${testIdPrefix}-${entry.id}`}
        >
          <View className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: entry.color }} />
          <Text variant="body-sm">{entry.label}</Text>
        </View>
      ))}
    </View>
  )
}
