// apps/web/src/features/transactions-list/components/TransactionListItem.vue
<script setup lang="ts">
import { formatCurrency } from '@/shared/lib/money/format'
import { isTransferTransaction } from '@/entities/transaction'
import { useAccounts } from '@/entities/account'
import { useCategories } from '@/entities/category'
import type { Transaction } from '@/entities/transaction'
import { useDateFormat } from '@vueuse/core'
import { RepeatIcon } from '@lucide/vue'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useSettingsStore } from '@/shared/stores/use-settings-store'

const { transaction } = defineProps<{ transaction: Transaction }>()
const { locale, t } = useI18n()
const settings = useSettingsStore()
const format = (value: number) => formatCurrency(value, settings.currency, locale.value)
const { data: categories } = useCategories()
const { data: accounts } = useAccounts()

const category = computed(() => {
  return categories.value?.find((category) => category.id === transaction.categoryId)
})

const account = computed(() => {
  if (isTransferTransaction(transaction)) {
    return undefined
  }
  return accounts.value?.find((account) => account.id === transaction.accountId)
})
const fromAccount = computed(() => {
  if (isTransferTransaction(transaction)) {
    return accounts.value?.find((account) => account.id === transaction.fromAccountId)
  }
  return undefined
})
const toAccount = computed(() => {
  if (isTransferTransaction(transaction)) {
    return accounts.value?.find((account) => account.id === transaction.toAccountId)
  }
  return undefined
})

const formattedOccuredAt = useDateFormat(transaction.occurredAt, 'DD MMM YYYY HH:mm', {
  locales: locale.value,
})

const isTransfer = computed(() => isTransferTransaction(transaction))
</script>

<template>
  <li class="flex items-center gap-3 px-3 py-2 border rounded-md">
    <div
      v-if="category"
      class="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-sm"
    >
      {{ category.icon }}
    </div>
    <div
      v-if="isTransfer"
      class="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-sm"
    >
      <RepeatIcon class="size-4" />
    </div>
    <div class="flex-1">
      <p v-if="transaction.description" class="text-sm font-medium">
        {{ transaction.description }}
      </p>
      <p class="text-xs text-muted-foreground">
        <template v-if="isTransfer">
          <span v-if="fromAccount && toAccount">
            {{ fromAccount.name }} -> {{ toAccount.name }}
          </span>
          <span v-else>{{ t('transactions.types.transfer') }}</span>
          · <span>{{ formattedOccuredAt }}</span>
        </template>
        <template v-else>
          <span v-if="category">
            {{ category.name }}
          </span>
          · <span v-if="account">{{ account.name }}</span> · <span>{{ formattedOccuredAt }}</span>
        </template>
      </p>
    </div>
    <p
      class="text-sm font-medium"
      :class="{
        'text-green-500': transaction.type === 'income',
        'text-red-500': transaction.type === 'expense',
        'text-foreground': transaction.type === 'transfer',
      }"
    >
      <span v-if="transaction.type === 'income'">+</span>
      <span v-if="transaction.type === 'expense'">-</span>
      <span>{{ format(transaction.amount) }}</span>
    </p>
  </li>
</template>

// apps/mobile/src/entities/transaction/ui/TransactionListItem.tsx
import { useTranslation } from 'react-i18next'
import { ListRow, Text } from '@shared/ui'
import { formatAmount } from '@shared/lib/format'
import { useSettingsStore } from '@shared/store/use-settings-store'
import type { CurrencyCode } from '@expense-tracker/money'
import { isTransferTransaction } from '@expense-tracker/api'
import type { AccountWithBalance, Category, Transaction } from '@expense-tracker/api'
import type { AppLocale } from '@expense-tracker/i18n'

const TRANSFER_ICON = '🔄'

interface TransactionListItemProps {
  transaction: Transaction
  /** Accounts, to resolve names + currency. Optional while loading. */
  accounts?: AccountWithBalance[]
  /** Categories, to resolve the cashflow title + icon. Optional while loading. */
  categories?: Category[]
}

/**
 * A single transaction row (design section 9 "list row"). The canonical item
 * reused by the Home recent list and the Transactions screen: leading category
 * icon, primary title, secondary subtitle, trailing amount.
 *
 * Per the mobile design the only saturated chrome color is destructive red, so
 * amounts are foreground-toned with a direction sign (+ income / - expense);
 * no green/red coloring. Money is formatted with tabular numerals in the
 * account's currency.
 */
export function TransactionListItem({
  transaction,
  accounts,
  categories,
}: TransactionListItemProps) {
  const { t } = useTranslation()
  const locale = useSettingsStore((state) => state.locale) as AppLocale
  const fallbackCurrency = useSettingsStore((state) => state.currency)

  const accountName = (id: string | undefined): string =>
    accounts?.find((account) => account.id === id)?.name ?? ''
  const accountCurrency = (id: string | undefined): CurrencyCode =>
    accounts?.find((account) => account.id === id)?.currency ?? fallbackCurrency

  if (isTransferTransaction(transaction)) {
    const from = accountName(transaction.fromAccountId)
    const to = accountName(transaction.toAccountId)
    const currency = accountCurrency(transaction.fromAccountId)
    const route = from && to ? `${from} → ${to}` : t('transactions.types.transfer')

    return (
      <ListRow
        leading={<Text size="title">{TRANSFER_ICON}</Text>}
        trailing={<RowTrailing amount={transaction.amount} currency={currency} locale={locale} />}
        divider={false}
      >
        <Text weight={500} numberOfLines={1}>
          {transaction.description || route}
        </Text>
        {transaction.description ? (
          <Text size="caption" tone="muted" numberOfLines={1}>
            {route}
          </Text>
        ) : null}
      </ListRow>
    )
  }

  const category = categories?.find((item) => item.id === transaction.categoryId)
  const currency = accountCurrency(transaction.accountId)
  const categoryName = category?.name ?? t(`transactions.types.${transaction.type}`)
  const account = accountName(transaction.accountId)
  const primary = transaction.description || categoryName
  const secondary = transaction.description ? `${categoryName} · ${account}`.trim() : account || categoryName

  return (
    <ListRow
      leading={<Text size="title">{category?.icon ?? '💸'}</Text>}
      trailing={
        <RowTrailing
          amount={transaction.amount}
          currency={currency}
          locale={locale}
          sign={transaction.type === 'income' ? '+' : '−'}
        />
      }
      divider={false}
    >
      <Text weight={500} numberOfLines={1}>
        {primary}
      </Text>
      <Text size="caption" tone="muted" numberOfLines={1}>
        {secondary}
      </Text>
    </ListRow>
  )
}

interface RowTrailingProps {
  amount: number
  currency: CurrencyCode
  locale: AppLocale
  sign?: '+' | '−'
}

function RowTrailing({ amount, currency, locale, sign }: RowTrailingProps) {
  const formatted = formatAmount(amount, currency, locale)
  return (
    <Text weight={600} tabular>
      {sign ? `${sign} ${formatted}` : formatted}
    </Text>
  )
}
